### ISSUE TITLE
Recreate momentum system

### ISSUE THREAD

**Issue by MaroonCoffee** [2021rkim/aepi-booth-24-arcade#8]
Joust is hard because it's extremely hard to change directions in the air, penalizing bad movement and increasing the effects of hitting a platform. This is mitigated by it being much easier to change directions while on the ground, allowing for some complexity in strategy (when to land vs when to be flying). Since momentum is always the same in the current build, this system needs to be replicated in some way.

See this emulator for the physics "feel": https://www.free80sarcade.com/joust.php

**Comment by 2021rkim** [comment]
Might want to look into the X-momentum push field here for this. Tested it out and it pushes you in a way you would expect https://docs.codehaus.moe/#/reference/player
